export interface Language {
  countryCode?: string; // ISO 3166-1 alpha-2 country code for flag
  label: string;
  value: string;
}

export const LANGUAGES: Language[] = [
  { value: "auto", label: "Auto Detect" }, // No flag for auto
  { value: "en", label: "English", countryCode: "GB" },
  { value: "zh-Hans", label: "Simplified Chinese", countryCode: "CN" },
  { value: "zh-Hant", label: "Traditional Chinese", countryCode: "TW" },
  { value: "de", label: "German", countryCode: "DE" },
  { value: "es", label: "Spanish", countryCode: "ES" },
  { value: "ru", label: "Russian", countryCode: "RU" },
  { value: "ko", label: "Korean", countryCode: "KR" },
  { value: "fr", label: "French", countryCode: "FR" },
  { value: "ja", label: "Japanese", countryCode: "JP" },
  { value: "pt", label: "Portuguese", countryCode: "PT" },
  { value: "tr", label: "Turkish", countryCode: "TR" },
  { value: "pl", label: "Polish", countryCode: "PL" },
  { value: "ca", label: "Catalan", countryCode: "ES" },
  { value: "nl", label: "Dutch", countryCode: "NL" },
  { value: "ar", label: "Arabic", countryCode: "SA" },
  { value: "sv", label: "Swedish", countryCode: "SE" },
  { value: "it", label: "Italian", countryCode: "IT" },
  { value: "id", label: "Indonesian", countryCode: "ID" },
  { value: "hi", label: "Hindi", countryCode: "IN" },
  { value: "fi", label: "Finnish", countryCode: "FI" },
  { value: "vi", label: "Vietnamese", countryCode: "VN" },
  { value: "he", label: "Hebrew", countryCode: "IL" },
  { value: "uk", label: "Ukrainian", countryCode: "UA" },
  { value: "el", label: "Greek", countryCode: "GR" },
  { value: "ms", label: "Malay", countryCode: "MY" },
  { value: "cs", label: "Czech", countryCode: "CZ" },
  { value: "ro", label: "Romanian", countryCode: "RO" },
  { value: "da", label: "Danish", countryCode: "DK" },
  { value: "hu", label: "Hungarian", countryCode: "HU" },
  { value: "ta", label: "Tamil", countryCode: "IN" },
  { value: "no", label: "Norwegian", countryCode: "NO" },
  { value: "th", label: "Thai", countryCode: "TH" },
  { value: "ur", label: "Urdu", countryCode: "PK" },
  { value: "hr", label: "Croatian", countryCode: "HR" },
  { value: "bg", label: "Bulgarian", countryCode: "BG" },
  { value: "lt", label: "Lithuanian", countryCode: "LT" },
  { value: "la", label: "Latin", countryCode: "VA" },
  { value: "mi", label: "Maori", countryCode: "NZ" },
  { value: "ml", label: "Malayalam", countryCode: "IN" },
  { value: "cy", label: "Welsh", countryCode: "GB" },
  { value: "sk", label: "Slovak", countryCode: "SK" },
  { value: "te", label: "Telugu", countryCode: "IN" },
  { value: "fa", label: "Persian", countryCode: "IR" },
  { value: "lv", label: "Latvian", countryCode: "LV" },
  { value: "bn", label: "Bengali", countryCode: "BD" },
  { value: "sr", label: "Serbian", countryCode: "RS" },
  { value: "az", label: "Azerbaijani", countryCode: "AZ" },
  { value: "sl", label: "Slovenian", countryCode: "SI" },
  { value: "kn", label: "Kannada", countryCode: "IN" },
  { value: "et", label: "Estonian", countryCode: "EE" },
  { value: "mk", label: "Macedonian", countryCode: "MK" },
  { value: "br", label: "Breton", countryCode: "FR" },
];
