export interface Language {
  countryCode?: string; // ISO 3166-1 alpha-2 country code for flag
  label: string;
  value: string;
}

export const LANGUAGES: Language[] = [
  { label: "Auto Detect", value: "auto" }, // No flag for auto
  { countryCode: "GB", label: "English", value: "en" },
  { countryCode: "CN", label: "Simplified Chinese", value: "zh-Hans" },
  { countryCode: "TW", label: "Traditional Chinese", value: "zh-Hant" },
  { countryCode: "DE", label: "German", value: "de" },
  { countryCode: "ES", label: "Spanish", value: "es" },
  { countryCode: "RU", label: "Russian", value: "ru" },
  { countryCode: "KR", label: "Korean", value: "ko" },
  { countryCode: "FR", label: "French", value: "fr" },
  { countryCode: "JP", label: "Japanese", value: "ja" },
  { countryCode: "PT", label: "Portuguese", value: "pt" },
  { countryCode: "TR", label: "Turkish", value: "tr" },
  { countryCode: "PL", label: "Polish", value: "pl" },
  { countryCode: "ES", label: "Catalan", value: "ca" },
  { countryCode: "NL", label: "Dutch", value: "nl" },
  { countryCode: "SA", label: "Arabic", value: "ar" },
  { countryCode: "SE", label: "Swedish", value: "sv" },
  { countryCode: "IT", label: "Italian", value: "it" },
  { countryCode: "ID", label: "Indonesian", value: "id" },
  { countryCode: "IN", label: "Hindi", value: "hi" },
  { countryCode: "FI", label: "Finnish", value: "fi" },
  { countryCode: "VN", label: "Vietnamese", value: "vi" },
  { countryCode: "IL", label: "Hebrew", value: "he" },
  { countryCode: "UA", label: "Ukrainian", value: "uk" },
  { countryCode: "GR", label: "Greek", value: "el" },
  { countryCode: "MY", label: "Malay", value: "ms" },
  { countryCode: "CZ", label: "Czech", value: "cs" },
  { countryCode: "RO", label: "Romanian", value: "ro" },
  { countryCode: "DK", label: "Danish", value: "da" },
  { countryCode: "HU", label: "Hungarian", value: "hu" },
  { countryCode: "IN", label: "Tamil", value: "ta" },
  { countryCode: "NO", label: "Norwegian", value: "no" },
  { countryCode: "TH", label: "Thai", value: "th" },
  { countryCode: "PK", label: "Urdu", value: "ur" },
  { countryCode: "HR", label: "Croatian", value: "hr" },
  { countryCode: "BG", label: "Bulgarian", value: "bg" },
  { countryCode: "LT", label: "Lithuanian", value: "lt" },
  { countryCode: "VA", label: "Latin", value: "la" },
  { countryCode: "NZ", label: "Maori", value: "mi" },
  { countryCode: "IN", label: "Malayalam", value: "ml" },
  { countryCode: "GB", label: "Welsh", value: "cy" },
  { countryCode: "SK", label: "Slovak", value: "sk" },
  { countryCode: "IN", label: "Telugu", value: "te" },
  { countryCode: "IR", label: "Persian", value: "fa" },
  { countryCode: "LV", label: "Latvian", value: "lv" },
  { countryCode: "BD", label: "Bengali", value: "bn" },
  { countryCode: "RS", label: "Serbian", value: "sr" },
  { countryCode: "AZ", label: "Azerbaijani", value: "az" },
  { countryCode: "SI", label: "Slovenian", value: "sl" },
  { countryCode: "IN", label: "Kannada", value: "kn" },
  { countryCode: "EE", label: "Estonian", value: "et" },
  { countryCode: "MK", label: "Macedonian", value: "mk" },
  { countryCode: "FR", label: "Breton", value: "br" },
];
